AllCops:
  TargetRubyVersion: 2.5.1

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
